export const EMPLOYEE_TYPES = {
    FETCH_ALL: 'EMPLOYEES/FETCH_EMPLOYEES',
    ADD_EMPLOYEE: 'EMPLOYEES/ADD_EMPLOYEE',
    UPDATE_EMPLOYEE: 'EMPLOYEES/UPDATE_EMPLOYEE',
    DELETE_EMPLOYEE: 'EMPLOYEES/DELETE_EMPLOYEE'
}