export const EMPLOYEE_TYPES = {
    FETCH_ALL: 'EMPLOYEES/FETCH_EMPLOYEES',
    ADD_EMPLOYEE: 'EMPLOYEES/ADD_EMPLOYEE',
    UPDATE_EMPLOYEE: 'EMPLOYEES/UPDATE_EMPLOYEE',
    DELETE_EMPLOYEE: 'EMPLOYEES/DELETE_EMPLOYEE'
};

export const POSITION_TYPES = {
    FETCH_ALL: 'POSITIONS/FETCH_POSITIONS',
    ADD_POSITION: 'POSITIONS/ADD_POSITION',
    UPDATE_POSITION: 'POSITIONS/UPDATE_POSITION',
    DELETE_POSITION: 'POSITIONS/DELETE_POSITION',
};

export const REPORTS_TYPES = {
    FETCH_LAST_REPORTS: 'REPORTS/FETCH_LAST_REPORTS',
    FETCH_MONTHLY_REPORTS: 'REPORTS/FETCH_MONTHLY_REPORTS',
    ADD_REPORT: 'REPORTS/ADD_REPORT',
    UPDATE_REPORT: 'REPORTS/UPDATE_REPORT',
    DELETE_REPORT: 'REPORTS/DELETE_REPORT',
    GET_REPORT: 'REPORTS/GET_REPORT',
    ADD_WORK_ITEM_REPORT: 'REPORTS/ADD_WORK_ITEM_REPORT',
    UPDATE_WORK_ITEM_REPORT: 'REPORTS/UPDATE_WORK_ITEM_REPORT',
    DELETE_WORK_ITEM_REPORT: 'REPORTS/DELETE_WORK_ITEM_REPORT',
    ADD_EMPLOYEE_ITEM_REPORT: 'REPORTS/ADD_EMPLOYEE_ITEM_REPORT',
    UPDATE_EMPLOYEE_ITEM_REPORT: 'REPORTS/UPDATE_EMPLOYEE_ITEM_REPORT',
    DELETE_EMPLOYEE_ITEM_REPORT: 'REPORTS/DELETE_EMPLOYEE_ITEM_REPORT',
    SET_DAY_STAT_REPORT: 'REPORTS/SET_DAY_STAT_REPORT',
    CREATE_EMPTY_REPORT: 'REPORTS/CREATE_EMPTY_REPORT',
    LOAD_SELECTED_EMPLOYEE_ITEM: 'REPORTS/LOAD_SELECTED_EMPLOYEE_ITEM',
};

export const FORM_INPUT_UPDATE = 'FORM_INPUT_UPDATE';