export const EMPLOYEE_TYPES = {
    FETCH_ALL: 'EMPLOYEES/FETCH_EMPLOYEES',
    ADD_EMPLOYEE: 'EMPLOYEES/ADD_EMPLOYEE',
    UPDATE_EMPLOYEE: 'EMPLOYEES/UPDATE_EMPLOYEE',
    DELETE_EMPLOYEE: 'EMPLOYEES/DELETE_EMPLOYEE',
    FIRE_EMPLOYEE: 'EMPLOYEES/FIRE_EMPLOYEE',
    START_LOADING: 'EMPLOYEES/START_LOADING',
    END_LOADING: 'EMPLOYEES/END_LOADING',
    SET_ERROR: 'EMPLOYEES/SET_ERROR',
};

export const POSITION_TYPES = {
    FETCH_ALL: 'POSITIONS/FETCH_POSITIONS',
    START_LOADING: 'POSITIONS/START_LOADING',
    END_LOADING: 'POSITIONS/END_LOADING',
    ADD_POSITION: 'POSITIONS/ADD_POSITION',
    UPDATE_POSITION: 'POSITIONS/UPDATE_POSITION',
    DELETE_POSITION: 'POSITIONS/DELETE_POSITION',
    SET_ERROR: 'POSITIONS/SET_ERROR',
};

export const REPORTS_TYPES = {
    SET_ERROR: 'REPORTS/SET_ERROR',
    START_LOADING: 'REPORTS/START_LOADING',
    END_LOADING: 'REPORTS/END_LOADING',
    FETCH_LAST_REPORTS: 'REPORTS/FETCH_LAST_REPORTS',
    FETCH_MONTHLY_REPORTS: 'REPORTS/FETCH_MONTHLY_REPORTS',
    ADD_REPORT: 'REPORTS/ADD_REPORT',
    UPDATE_REPORT: 'REPORTS/UPDATE_REPORT',
    DELETE_REPORT: 'REPORTS/DELETE_REPORT',
    GET_REPORT: 'REPORTS/GET_REPORT',
    ADD_WORK_ITEM_REPORT: 'REPORTS/ADD_WORK_ITEM_REPORT',
    UPDATE_WORK_ITEM_REPORT: 'REPORTS/UPDATE_WORK_ITEM_REPORT',
    DELETE_WORK_ITEM_REPORT: 'REPORTS/DELETE_WORK_ITEM_REPORT',
    ADD_EMPLOYEE_ITEM_REPORT: 'REPORTS/ADD_EMPLOYEE_ITEM_REPORT',
    UPDATE_EMPLOYEE_ITEM_REPORT: 'REPORTS/UPDATE_EMPLOYEE_ITEM_REPORT',
    DELETE_EMPLOYEE_ITEM_REPORT: 'REPORTS/DELETE_EMPLOYEE_ITEM_REPORT',
    SET_DAY_STAT_REPORT: 'REPORTS/SET_DAY_STAT_REPORT',
    CREATE_EMPTY_REPORT: 'REPORTS/CREATE_EMPTY_REPORT',
    LOAD_SELECTED_EMPLOYEE_ITEM: 'REPORTS/LOAD_SELECTED_EMPLOYEE_ITEM',
};

export const COMPANY_TYPES = {
    SET_ERROR: 'COMPANY/SET_ERROR',
    START_LOADING: 'COMPANY/START_LOADING',
    END_LOADING: 'COMPANY/END_LOADING',
    FETCH_AVG_SALARY_ON_DAY: 'COMPANY/FETCH_AVG_SALARY_ON_DAY',
    FETCH_COUNT_EMPLOYEES: 'COMPANY/FETCH_COUNT_EMPLOYEES'
};

export const STAT_TYPES = {
    SET_ERROR: 'STAT/SET_ERROR',
    START_LOADING: 'STAT/START_LOADING',
    END_LOADING: 'STAT/END_LOADING',
    FETCH_EMPLOYEE_STAT: 'STAT/FETCH_EMPLOYEE_STAT',
    FETCH_STAT_BY_EMPLOYEE: 'STAT/FETCH_STAT_BY_EMPLOYEE'
}

export const STORAGE_TYPES = {
    FETCH_ACTUAL_STORAGE: 'STORAGE_TYPES/FETCH_ACTUAL_STORAGE',
    FETCH_UNLOADING_EVENTS: 'STORAGE_TYPES/FETCH_UNLOADING_EVENTS',
    ADD_UNLOADING_EVENT: 'STORAGE_TYPES/ADD_UNLOADING_EVENT',
    DELETE_UNLOADING_EVENT: 'STORAGE_TYPES/DELETE_UNLOADING_EVENT',
}

export const AUTH_TYPES = {
    SET_USER: 'AUTH_TYPES/SET_USER',
    SET_ACCESS_TOKEN: 'AUTH_TYPES/SET_ACCESS_TOKEN',
    SET_REFRESH_TOKEN: 'AUTH_TYPES/SET_REFRESH_TOKEN',
    TRY_AUTO_LOGIN: 'AUTH_TYPES/TRY_AUTO_LOGIN',
    START_LOADING: 'AUTH_TYPES/START_LOADING',
    END_LOADING: 'AUTH_TYPES/END_LOADING',
    LOG_OUT: 'AUTH_TYPES/LOG_OUT',
}

export const USER_TYPES = {
    SET_AVG_MONTH_SALARY: 'USER_TYPES/SET_AVG_MONTH_SALARY',
    FETCH_AVG_MONTH_SALARY: 'USER_TYPES/SET_AVG_MONTH_SALARY',
    SET_TOTAL_MONTH_SALARY: 'USER_TYPES/SET_TOTAL_MONTH_SALARY',
    FETCH_TOTAL_MONTH_SALARY: 'USER_TYPES/SET_TOTAL_MONTH_SALARY',
    FETCH_USER_DATA: 'USER_TYPES/FETCH_USER_DATA',

    SET_ERROR: 'USER_TYPES/SET_ERROR',
    START_LOADING: 'USER_TYPES/START_LOADING',
    END_LOADING: 'USER_TYPES/END_LOADING'
}

export const FORM_INPUT_UPDATE = 'FORM_INPUT_UPDATE';