export const AUTH_TYPES = {
    SET_USER: 'AUTH_TYPES/SET_USER',
    FETCH_USER: 'AUTH_TYPES/FETCH_USER',
    SET_ACCESS_TOKEN: 'AUTH_TYPES/SET_ACCESS_TOKEN',
    SET_REFRESH_TOKEN: 'AUTH_TYPES/SET_REFRESH_TOKEN',
    TRY_AUTO_LOGIN: 'AUTH_TYPES/TRY_AUTO_LOGIN',
    FINISH_AUTO_LOGIN: 'AUTH_TYPES/FINISH_AUTO_LOGIN',
    START_LOADING: 'AUTH_TYPES/START_LOADING',
    END_LOADING: 'AUTH_TYPES/END_LOADING',
    SET_ERROR: 'AUTH_TYPES/SET_ERROR',
    LOG_IN: 'AUTH_TYPES/LOG_IN',
};

export const POSITION_TYPES = {
    FETCH_ALL: 'POSITIONS/FETCH_POSITIONS',
    START_LOADING: 'POSITIONS/START_LOADING',
    END_LOADING: 'POSITIONS/END_LOADING',
    ADD_POSITION: 'POSITIONS/ADD_POSITION',
    UPDATE_POSITION: 'POSITIONS/UPDATE_POSITION',
    DELETE_POSITION: 'POSITIONS/DELETE_POSITION',
    SET_ERROR: 'POSITIONS/SET_ERROR',
};

export const EMPLOYEE_TYPES = {
    FETCH_ALL: 'EMPLOYEES/FETCH_EMPLOYEES',
    ADD_EMPLOYEE: 'EMPLOYEES/ADD_EMPLOYEE',
    UPDATE_EMPLOYEE: 'EMPLOYEES/UPDATE_EMPLOYEE',
    DELETE_EMPLOYEE: 'EMPLOYEES/DELETE_EMPLOYEE',
    FIRE_EMPLOYEE: 'EMPLOYEES/FIRE_EMPLOYEE',
    START_LOADING: 'EMPLOYEES/START_LOADING',
    END_LOADING: 'EMPLOYEES/END_LOADING',
    SET_ERROR: 'EMPLOYEES/SET_ERROR',
};


export const STORAGE_TYPES = {
    FETCH_ACTUAL_STORAGE: 'STORAGE_TYPES/FETCH_ACTUAL_STORAGE',
    FETCH_UNLOADING_EVENTS: 'STORAGE_TYPES/FETCH_UNLOADING_EVENTS',
    ADD_UNLOADING_EVENT: 'STORAGE_TYPES/ADD_UNLOADING_EVENT',
    DELETE_UNLOADING_EVENT: 'STORAGE_TYPES/DELETE_UNLOADING_EVENT',

    START_LOADING: 'STORAGE_TYPES/START_LOADING',
    END_LOADING: 'STORAGE_TYPES/END_LOADING'
};

export const COMPANY_TYPES = {
    SET_ERROR: 'COMPANY/SET_ERROR',
    START_LOADING: 'COMPANY/START_LOADING',
    END_LOADING: 'COMPANY/END_LOADING',

    FETCH_COMPANY_DATA: 'COMPANY/FETCH_COMPANY_DATA',

    FETCH_AVG_SALARY_ON_DAY: 'COMPANY/FETCH_AVG_SALARY_ON_DAY',
    SET_AVG_SALARY_ON_DAY: 'COMPANY/FETCH_AVG_SALARY_ON_DAY',

    FETCH_COUNT_EMPLOYEES: 'COMPANY/FETCH_COUNT_EMPLOYEES',
    SET_COUNT_EMPLOYEES: 'COMPANY/FETCH_COUNT_EMPLOYEES'
};

export const REPORT_TYPES = {
    SET_ERROR: 'REPORTS/SET_ERROR',
    START_LOADING: 'REPORTS/START_LOADING',
    END_LOADING: 'REPORTS/END_LOADING',

    FETCH_MONTHLY_REPORTS: 'REPORTS/FETCH_MONTHLY_REPORTS',
    SET_MONTHLY_REPORTS: 'REPORTS/SET_MONTHLY_REPORTS'
}