export const AUTH_TYPES = {
    SET_USER: 'AUTH_TYPES/SET_USER',
    FETCH_USER: 'AUTH_TYPES/FETCH_USER',
    SET_ACCESS_TOKEN: 'AUTH_TYPES/SET_ACCESS_TOKEN',
    SET_REFRESH_TOKEN: 'AUTH_TYPES/SET_REFRESH_TOKEN',
    TRY_AUTO_LOGIN: 'AUTH_TYPES/TRY_AUTO_LOGIN',
    FINISH_AUTO_LOGIN: 'AUTH_TYPES/FINISH_AUTO_LOGIN',
    START_LOADING: 'AUTH_TYPES/START_LOADING',
    END_LOADING: 'AUTH_TYPES/END_LOADING',
    SET_ERROR: 'AUTH_TYPES/SET_ERROR',
    LOG_IN: 'AUTH_TYPES/LOG_IN',
};

export const POSITION_TYPES = {
    FETCH_ALL: 'POSITIONS/FETCH_POSITIONS',
    START_LOADING: 'POSITIONS/START_LOADING',
    END_LOADING: 'POSITIONS/END_LOADING',
    ADD_POSITION: 'POSITIONS/ADD_POSITION',
    UPDATE_POSITION: 'POSITIONS/UPDATE_POSITION',
    DELETE_POSITION: 'POSITIONS/DELETE_POSITION',
    SET_ERROR: 'POSITIONS/SET_ERROR',
};

export const EMPLOYEE_TYPES = {
    FETCH_ALL: 'EMPLOYEES/FETCH_EMPLOYEES',
    ADD_EMPLOYEE: 'EMPLOYEES/ADD_EMPLOYEE',
    UPDATE_EMPLOYEE: 'EMPLOYEES/UPDATE_EMPLOYEE',
    DELETE_EMPLOYEE: 'EMPLOYEES/DELETE_EMPLOYEE',
    FIRE_EMPLOYEE: 'EMPLOYEES/FIRE_EMPLOYEE',
    START_LOADING: 'EMPLOYEES/START_LOADING',
    END_LOADING: 'EMPLOYEES/END_LOADING',
    SET_ERROR: 'EMPLOYEES/SET_ERROR',
};