export const AUTH_TYPES = {
    SET_USER: 'AUTH_TYPES/SET_USER',
    FETCH_USER: 'AUTH_TYPES/FETCH_USER',
    SET_ACCESS_TOKEN: 'AUTH_TYPES/SET_ACCESS_TOKEN',
    SET_REFRESH_TOKEN: 'AUTH_TYPES/SET_REFRESH_TOKEN',
    TRY_AUTO_LOGIN: 'AUTH_TYPES/TRY_AUTO_LOGIN',
    START_LOADING: 'AUTH_TYPES/START_LOADING',
    END_LOADING: 'AUTH_TYPES/END_LOADING',
    SET_ERROR: 'AUTH_TYPES/SET_ERROR',
    LOG_IN: 'AUTH_TYPES/LOG_IN',
}