export const CREATE_POSITION = 'POSITION/CREATE_POSITION'
export const FETCH_POSITIONS = 'POSITION/FETCH_POSITIONS'
export const UPDATE_POSITION = 'POSITION/UPDATE_POSITION'
export const DELETE_POSITION = 'POSITION/DELETE_POSITION'

export const CREATE_EMPLOYEE = 'EMPLOYEE/CREATE_EMPLOYEE'
export const FETCH_EMPLOYEES = 'EMPLOYEE/FETCH_EMPLOYEES'
export const UPDATE_EMPLOYEE = 'EMPLOYEE/UPDATE_EMPLOYEE'
export const DELETE_EMPLOYEE = 'EMPLOYEE/DELETE_EMPLOYEE'

export const SHOW_LOADER = 'APP/SHOW_LOADER'
export const HIDE_LOADER = 'APP/HIDE_LOADER'
export const SHOW_ALERT = 'APP/SHOW_ALERT'
export const HIDE_ALERT = 'APP/HIDE_ALERT'

export const SERVER_URL = 'http://127.0.0.1:8080'

export const actionType = {
    CREATE: 'CREATE',
    UPDATE: 'UPDATE',
    FETCH_ALL: 'FETCH_ALL',
    DELETE: 'DELETE'
}